version: "3"

services:
    name: staticWebsite
    client:
        image: nginx
        name: staticWebsite
        ports:
            - 5454:80
        volumes:
            - ./src:/usr/share/nginx/html
